version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PerfectPersonnelPlacement"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cevoddeymacb"
s3_prefix = "PerfectPersonnelPlacement"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repository = "319115845002.dkr.ecr.us-east-2.amazonaws.com/perfect-personnel-placement"
