on:
  # Trigger analysis when pushing in dev-branch or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - Dev-Branch
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
name: Dev Workflow

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.2.0
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get dev
      run: git fetch origin Dev-Branch
    - name: Install dependencies
      run:  npm install
    - name: Install Jest globally
      run:  sudo npm install -g jest
    - name: Run Tests
      # run:  npm run test 'src/trainer/createTrainerFn/createTrainer.test.ts'
      run: npm run test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      # with:
      #   projectBaseDir: './backend/src'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
